name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    env:
      API_STACK_CDK_NAME: BackendServiceStack
      API_GW_STACK_CDK_NAME: ApiGwStack
      API_STACK_NAME: dev-backend-service
      API_ENVIRONMENT: dev
      AWS_REGION: eu-central-1

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -D esbuild
    - run: cd infrastructure
    - run: npm ci
    - run: npm run cdk --deploy ${{ env.API_STACK_CDK_NAME }} --context environment=${{ env.API_ENVIRONMENT }} --require-approval never --parameters ${{ env.API_STACK_NAME }}:ImageTag=${{ github.sha }}
